### ISSUE TITLE
Integer之你所不知道的bug | 何处有所栖

### ISSUE THREAD

**Issue by guopengd** [guopengd/guopengd.github.io#10]
https://blog.gpdstudy.club/2019/06/16/integer-erro/#more 

 bug缘起今天日常在牛客群里和小伙伴们吹水聊天，我聊到代码规范的时候吐槽了一波，公司每个人的代码规范都不统一，int和integer有的人用equals有的人用==。然后建议统一用equals。于是贴了一波代码为了佐证一下我的建议吧。代码如下: 1234567int i = 1;Integer b = null;if(a == b) &#123;    System.out.println(tru

**Comment by Rukawalee** [comment]
支持泡佬，百忙之中抽取空闲时间，码字1250，为我们详述Integer之BUG，有幸学习到泡佬的见解，实则让晚生佩服得五体投地。

**Comment by 51461** [comment]
冒泡大佬牛皮

**Comment by 51461** [comment]
# 冒泡大佬牛皮

**Comment by Rukawalee** [comment]
<h3 align="center">冒泡大佬tql</h3>
<p>大佬才华横溢，可是我要找的冒泡大佬？</p>

**Comment by guopengd** [comment]
> @Rukawalee
> <h3 align="center">冒泡大佬tql</h3>
> <p>大佬才华横溢，可是我要找的冒泡大佬？</p>

你们能不能正常点，不要皮

**Comment by 51461** [comment]
> @guopengd
> > @Rukawalee
> > <h3 align="center">冒泡大佬tql</h3>
> > <p>大佬才华横溢，可是我要找的冒泡大佬？</p>
> 
> 你们能不能正常点，不要皮

# 我觉得我们挺正常的
[冒泡大佬牛皮](/images/active.jpg)

**Comment by Rukawalee** [comment]
> @guopengd
> > @Rukawalee
> > <h3 align="center">冒泡大佬tql</h3>
> > <p>大佬才华横溢，可是我要找的冒泡大佬？</p>
> 
> 你们能不能正常点，不要皮

<h1 align="center">挺正常的。</h1>

**Comment by Rukawalee** [comment]
> @51461
> > @guopengd
> > > @Rukawalee
> > > <h3 align="center">冒泡大佬tql</h3>
> > > <p>大佬才华横溢，可是我要找的冒泡大佬？</p>
> > 
> > 你们能不能正常点，不要皮
> 
> # 我觉得我们挺正常的
> [冒泡大佬牛皮](/images/active.jpg)
>>>>>>>>>
>>>>>>>>><h1 align="center" style="font-family: red;">这样是不是显示得多点</h1>

**Comment by guopengd** [comment]
> @Rukawalee
> > @51461
> > > @guopengd
> > > > @Rukawalee
> > > > <h3 align="center">冒泡大佬tql</h3>
> > > > <p>大佬才华横溢，可是我要找的冒泡大佬？</p>
> > > 
> > > 你们能不能正常点，不要皮
> > 
> > # 我觉得我们挺正常的
> > [冒泡大佬牛皮](/images/active.jpg)
> >>>>>>>>>
> >>>>>>>>><h1 align="center" style="font-family: red;">这样是不是显示得多点</h1>
> 

这样显得我没有人气。。。

**Comment by Rukawalee** [comment]
> @guopengd
> > @Rukawalee
> > > @51461
> > > > @guopengd
> > > > > @Rukawalee
> > > > > <h3 align="center">冒泡大佬tql</h3>
> > > > > <p>大佬才华横溢，可是我要找的冒泡大佬？</p>
> > > > 
> > > > 你们能不能正常点，不要皮
> > > 
> > > # 我觉得我们挺正常的
> > > [冒泡大佬牛皮](/images/active.jpg)
> > >>>>>>>>>
> > >>>>>>>>><h1 align="center" style="font-family: red;">这样是不是显示得多点</h1>
> > 
> 
> 这样显得我没有人气。。。

>>>我们去关注你的github
